name: Test Runner
env:
  NAME: 'test'
on:
  push:
    branches:
      - main
jobs:
  simple_test_pipeline:
    runs-on: ubuntu-20.04
    if: ${{ (github.event_name == 'push'||github.event_name == 'merge') && !contains(toJson(join(github.event.commits.*.message, ' ')),'#skipdeploy') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install,  test-coverage
        run: |
          npm install
          npm run coverage
      - name: Run Tests
        run: npm run test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
